spring:
  application:
    name: CLOUD-GATEWAY

  cloud:
    gateway:
      httpclient:
        connect-timeout: 25000       # 10 seconds in ms
        response-timeout: 30s        # 10 seconds as duration

logging:
  level:
    org.springframework.retry: DEBUG

server:
  port: 9090
