---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: basantanembang10/h-booking-service:latest
        
          ports:
          - containerPort: 8082

          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: booking-service-cmap
                  key: config_uri       

            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: booking-service-cmap
                  key: mongodb_uri     

            - name: SPRING_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: booking-service-cmap
                  key: spring_bootstrap_servers   

            - name: SPRING_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: booking-service-cmap
                  key: spring_schema_registry_uri
          
            - name: HOTEL_URL
              valueFrom:
                configMapKeyRef:
                  name: booking-service-cmap
                  key: hotel_url   

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-service-cmap
data:
  config_uri: http://config-server-svc:9296
  mongodb_uri: "mongodb://root:password@mongodb-svc:27017/hotel-bookingdb?authSource=admin"
  spring_bootstrap_servers: broker:29092
  spring_schema_registry_uri: http://schema-registry-svc:8090
  hotel_url: http://hotel-service-svc.default.svc.cluster.local:8080


---

apiVersion: v1
kind: Service
metadata:
  name: booking-service-svc
spec:
  selector:
    app: booking-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082

    