---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: basantanembang10/h-inventory-service:latest
      
          ports:
          - containerPort: 8083

          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-service-cmap
                  key: config_uri

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: inventory-service-cmap
                  key: hostName     
                               
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1g"

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: inventory-service-cmap
                  key: spring_bootstrap_servers              

            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-service-cmap
                  key: spring_schema_registry_uri


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-cmap
data:
  config_uri: http://config-server-svc:9296
  hostName: mysql-svc:3306
  spring_bootstrap_servers: broker:29092
  spring_schema_registry_uri: http://schema-registry-svc:8090

 
---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
spec:
  selector:
    app: inventory-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083


