
server:
  port: 9296

spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BasantaNembang/Hotel-Web-App
          clone-on-start: true
