
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath: ##your machine location
    path: /run/desktop/mnt/host/c/temp/testfiles1
    type: DirectoryOrCreate

    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cmap
data:
  mongo_username: "root"
  mongo_db: "hotel-bookingdb"



---

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrect
data:
  mongo_password: "cGFzc3dvcmQ="   #encode by echo -n "your-password" | base64 (--decode for decoding) 


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                key: mongo_username
                name: mongodb-cmap    

          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: mongo_db
                name: mongodb-cmap

          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mongo_password
                name: mongodb-secrect            

        volumeMounts:
          - name: mongodb-p-storage
            mountPath: /data/db ##container location--> create folder-Name data/db to store data inside the conatiner
          

      volumes:  ##take stoarge form outside conatiner and gives to mongodb container 
        - name: mongodb-p-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc


## no need to write a script to create database for mongodb since it is created by spring boot itself............


---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
