---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/c/temp/testfiles"
    type: DirectoryOrCreate
    
   
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  



---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"  

          volumeMounts:
            - name: mysql-script-cmap
              mountPath: /docker-entrypoint-initdb.d

            - name: mysql-p-storage
              mountPath: /var/lib/mysql


      volumes:
        - name: mysql-p-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

        - name: mysql-script-cmap
          configMap:
            name: mysql-script

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS hoteldb;
    CREATE DATABASE IF NOT EXISTS avaiableroomdb;
    CREATE DATABASE IF NOT EXISTS paymentdb;
    CREATE DATABASE IF NOT EXISTS userdb;
        
 
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306

