
# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-pv
# spec:
#   capacity:
#     storage: 512Mi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: manual
#   hostPath: 
#     path: /run/desktop/mnt/host/c/temp/testfiles2
#     type: DirectoryOrCreate

    
# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc
# spec:
#   resources:
#     requests:
#       storage: 512Mi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: manual


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: redis
          image: redis:latest
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "no"  
            - "--bind"  #access from all netweork
            - "0.0.0.0" #access from all container 
            
          ports:
          - containerPort: 6379
          
      #     volumeMounts:
      #     - name: redis-p-storage
      #       mountPath: /data           

      # volumes:  
      #   - name: redis-p-storage
      #     persistentVolumeClaim:
      #       claimName: redis-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-app
  ports:
  - port: 6379
    targetPort: 6379
